### PR TITLE
suggestion only

### PR DESCRIPTION
**Pull request by Phil-Friderici**
hope you like it ;)

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
I see you have activated travis checking for this repo :+1:

**Comment by kylefu8** [comment]
Thanks for your suggestion! That's really nice for fix_haldaemon!

I have one more idea. Is it ok write like this logic? 
if (osfamily==Suse and lsbmajdistrelease==10&11) or (osfamily==Redhat and lsbmajdistrelease==5&6)
{
   All  functionalities here.
}
else
{
  fail("ltscore is only supported on Suse 10&11, Redhat 5&6.")
}

Then we can ignore the unsupported OS check inside all functionalities.

**Comment by Phil-Friderici** [comment]
It depends on the strategy. My strategy would be to not fail on unsupported OSfamilies until a functionality is activated. The other strategy would be to fail if the module is called on an unsupported OS.

#### Assumption:
I use hiera/osfamily/*.yaml files to configure which OSfamilies should actually use which functionallity of the module. I take care to only activate functionallity on supported OSfamilies. The module itself will be called without further configurations in a group definition.

#### Example for failing on functionallities:
With an Suse OSfamily it would start the module and use the functionallity which was configured in hiera/osfamily/Suse.yaml.

With unsupported OSfamily Solaris it would start the module and do nothing because I didn't activated any functionallity in hiera/osfamily/Solaris.yaml.

#### Example for failing on module:
With an Suse OSfamily it would start the module and use the functionallity which was configured in hiera/osfamily/Suse.yaml.

With unsupported OSfamily Solaris it would start the module and fail even when no functionallity was activated :(

**Comment by Phil-Friderici** [comment]
> Then we can ignore the unsupported OS check inside all functionalities.

Not all funtionallity is supported on all OSfamilies, you should still check and fail on them.

**Comment by kylefu8** [comment]
How about change the fail message to notify on my logic? That will not fail the puppet run. The module will do nothing either. Just a kindly message on the puppet client.
I understand your concern to each functionality. But that will only judge once to those unsupported OSes on my logic. And the function like fix_messages_permission and fix_localscratch_path will not be called on unsupported OSes even if they are not surrounded by the OS judgment code on each of them.

**Comment by Phil-Friderici** [comment]
Nice idea to use notice() instead of fail(). With fails you ***ensure*** that someone will see and cleanup the missconfiguration. A notice might easily end up in the sea of unread messages. That's the reason why I prefer fails in cases like this.

I think my style would be bring more benefit on modules that will end up to be used on more OSfamilies like the LTS only. Both ways will carry out what we need in the end :)

Choose your poison, I support both equally ;)

**Comment by kylefu8** [comment]
Thanks! I will think more about it and make the decision.
BTW, did I kill the zombie by changing 'case' to 'is_bool'?

**Comment by Phil-Friderici** [comment]
@kylefu8 Sorry, I didn't saw that change. Yes! you killed the zombie :) Congratulations !!!

**Comment by Phil-Friderici** [comment]
BTW: Beside some XP, you have looted the best weapon for boolean handling from the dead zombies :+1:

**Pull request merged**
